#!/usr/bin/env bash
# NIMA - UserBot
# Copyright (C) 2021-2025
#
# This file is a part of < https://github.com/nimesha206>
# PLease read the GNU Affero General Public License in <https://github.com/nimesha206/Telegram>.


echo "
            

      Visit @mjsicgroupsl for updates!!

"
if [ -f .env ] ; then  set -o allexport; source .env; set +o allexport ; fi
if [ $SESSION1 ] ; then python3 multi_client.py ; else python3 -m pyUltroid ; fi
